### ISSUE TITLE
line number

### ISSUE THREAD

**Issue by abernier** [dependents/node-dependency-tree#111]
Hi,

Is there a way to return the line (where the dependency was found) in addition to the filepath?

Thank you

**Comment by mrjoelkemp** [comment]
Hey! Not at the moment.

I believe we dangle the parsed ast after the precinct phase, so it's
possible to retraverse (should go behind a boolean flag) the ast to grab
the line numbers of the dependencies.

You'd then need to maintain that extra metadata as you resolve the
dependencies in the filing-cabinet phase.

I think it's possible without having to change the contract of all
detectives registered in precinct.

You could also fork and hack whatever you need into place if you don't want
to go with a PR contribution.

Cheers!
