### ISSUE TITLE
noTypeDefinitions usage

### ISSUE THREAD

**Issue by vinvol** [dependents/node-dependency-tree#115]
Hey all!

I saw that you bumped the version of node-filing-cabinet to 2.5.1 here in https://github.com/dependents/node-dependency-tree/commit/31c0ce5b9ca41c58e8f89ab96070418c9a46c806 , with support for `noTypeDefinitions`.

There doesn't seem to be a way to pass this as a param.
I'd be happy to make PR for this.

**Comment by mrjoelkemp** [comment]
Hey, sorry for the delay here. If you still have a need for this, I think a `cabinet` option that deep merges into the cabinet options here https://github.com/dependents/node-dependency-tree/blob/master/index.js#L104 could work. Would need a test that the newly merged in option actually works and it would need a readme change. 

If you don't have a need for this, we can just close it for now. Thanks!
