### ISSUE TITLE
Exclude unused import

### ISSUE THREAD

**Issue by zaniar** [dependents/node-dependency-tree#128]
Is it possible to exclude unused import?

**Comment by mrjoelkemp** [comment]
Hi! Can you provide an example so that I don't have wrong assumptions of what you mean? Thanks!

**Comment by zaniar** [comment]
For example:
```ts
// Example.ts

import a from 'A';
import b from 'B';

let x = b; // module B used
```
Currently the output is:
```js
{
  'Example.ts': {
    'A.ts': {},
    'B.ts': {}
  }
}
```
I need the output to be:
```js
{
  'Example.ts': {
    'B.ts': {}
  }
}
```

**Comment by mrjoelkemp** [comment]
Thanks for the example. That's not supported at the moment. It's nontrivial and a big lift. You'd have to do scope analysis to ensure that you're referring to the module b and not some variable b that's local to a function.

It's all doable, but I can't lead that effort. It would have to take someone from the community to spike on how to achieve this.

You could also make that a separate library that takes the dep tree and strips out unused imports. It would be slower with reparsing files for their AST, but if that's not an issue, then it's a straightforward path. 

I'll close this issue in favor of recommending that you or someone else create a library that strips out unused imports from the dep tree.

Thanks again for the request.
