### ISSUE TITLE
feat: list import tokens in dep tree

### ISSUE THREAD

**Issue by AndersDJohnson** [dependents/node-dependency-tree#147]
Hello! This is an awesome library! I was wondering how the maintainers would feel about the idea of adding a feature/option that would allow the dependency graph to include the names of the tokens being imported.

This might be a change to some of the detective packages as well, and perhaps only make sense in the case of JS/TS.

E.g., from:

```ts
{
  '/Users/anders/code/deps/src/examples/app/App.jsx': {
    '/Users/anders/code/deps/src/examples/app/components/Header.jsx': {
      '/Users/anders/code/js-usage/src/examples/app/components/Title.jsx': {}
    },
    '/Users/anders/code/js-usage/src/examples/app/components/Footer.jsx': {}
  }
}
```

To a structure with metadata like:

```ts
{
 path:  '/Users/anders/code/deps/src/examples/app/App.jsx',
 children: [
    {
      tokens: ['Header'],
      path: '/Users/anders/code/deps/src/examples/app/components/Header.jsx',
      children: [
        {
          tokens: ['Title'],
          path: '/Users/anders/code/deps/src/examples/app/components/Title.jsx'
        }
      ]
    },
    {
      tokens: ['Footer'],
      path: '/Users/anders/code/deps/src/examples/app/components/Footer.jsx'
    }
  }
}
```

If it's an import without tokens, we could say `tokens` would be either empty array `[]` or not defined at all.

If it's a default import, I suppose we could give something like `token: ['default']` or just omit `tokens` in this case as well.

**Comment by mrjoelkemp** [comment]
Hey! Given the effort and complexity of changes, it would be better to fork the relevant dependencies and put that feature in its own library. Minor fixes or improvements by the community are accepted, but not significant changes. Thanks for the idea contribution. 

Will close this as a wontfix. Thanks again.

**Comment by AndersDJohnson** [comment]
No worries @mrjoelkemp, I understand it's not an easy undertaking and hard enough to maintain as-is. I'll likely start working on smaller pieces and maybe end up just publishing forks. Starting here: https://github.com/dependents/detective-typescript/pull/47

**Comment by AndersDJohnson** [comment]
@mrjoelkemp I think I found a relatively lightweight way to solve it: https://github.com/dependents/detective-typescript/pull/48. Supporting a generic callback like that (and enough metadata to indicate position in tree to integrators) should eliminate the need for a lot of other feature requests.
