### ISSUE TITLE
System js support 

### ISSUE THREAD

**Issue by ghost** [dependents/node-dependency-tree#29]
@mrjoelkemp: Hi, I like your dependency-tree tool. But unfortunately it doesn't meet my requirements. I use [SystemsJS](https://github.com/systemjs/systemjs) that uses a `system.config.js` file to map the paths of modules to specific name. See below:

``` javascript
import * from 'angular'
import lodash from 'lodash'
```

with `'lodash'` declared in the `system.config.js` like so: 

``` javascript
'lodash' : 'node_modules/lodash/lodash.js'
'angular' : 'lib/angular/angular.js'
```

So essentially module path resolution should take place based on the keys in your `system.config.js` I've looked at the code and I would love to try my hand at adding support for SystemJS. I've already played with your code and I have the basics working.

**Comment by mrjoelkemp** [comment]
Hi Marthinus,

Thanks for contributing!

Webpack and SystemJS support are definitely items on the wish list. I'm
definitely open to PRs adding support for either.

Before a PR, I'd like to understand the changes that are necessary to
provide SystemJS support. Feel free to provide some notes in a comment on
this thread, or point me to your fork so that we can be on the same page.

It's definitely possible to add support in dependency-tree core, but my
hunch is that the resolution logic should happen at the filing-cabinet
level since that's the resolution factory. Happy to discuss further.

**Comment by marthinus-engelbrecht** [comment]
@mrjoelkemp: Yeah after looking at the code more I also came to the conclusion that it should be in filling cabinet somewhere around [here](https://github.com/mrjoelkemp/node-filing-cabinet/blob/master/index.js#L83). I believe it would simply be a matter of adding a lookup function specific to 'systemjs' that would just use it's config which is just an associative array to look up the full paths. Distinguishing between 'systemjs' and 'es6' modules would be a bit more tricky, but we can maybe just check if there are any forward slashes('/') in the path. I haven't forked anything yet, just did a clone. But If you cool with it I will fork filling-cabinet try the above suggestion and once I have something that works I will point you to it.

**Comment by marthinus-engelbrecht** [comment]
We might have to refactor [resolve-dependency-path](https://github.com/mrjoelkemp/node-resolve-dependency-path), to remove the SystemJS plugin handling [here](https://github.com/mrjoelkemp/node-resolve-dependency-path/blob/master/index.js#L62) and place it in the `systemLookup` function

**Comment by mrjoelkemp** [comment]
@marthinus-engelbrecht Thanks for looking into it.

I think we could introduce an artificial type `systemjs` here https://github.com/mrjoelkemp/node-filing-cabinet/blob/master/index.js#L78-L81. To not muddy a requirejs `config` with a systemjs or webpack config, we can introduce new params like `systemjsConfig` and `webpackConfig`. So if the module is es6 and we have a `systemjsConfig`, then we can say that the type is `systemjs` and use a custom systemjs resolver.

**Comment by mrjoelkemp** [comment]
We can also have dependency-tree support the new `systemjsConfig` option as a passthrough to filing-cabinet around here: https://github.com/mrjoelkemp/node-dependency-tree/blob/master/index.js#L190.

Happy to look at some code and help answer any questions you might have. Super excited for this!

**Comment by marthinus-engelbrecht** [comment]
Yeah that's what i've also been thinking. I'll see if I can get a chance to work on this tomorrow, otherwise Saturday.

**Comment by marthinus-engelbrecht** [comment]
As a side note. What made you decide to create this library instead of contributing to something like [madge](https://github.com/pahen/madge). I'm considering seeing if I can add support there as well?

**Comment by mrjoelkemp** [comment]
Great question. There's actually an open issue to [integrate dependency-tree into madge](https://github.com/pahen/madge/issues/68). Madge is a visualization tool that needs to trace the dependency tree as a pre-req; it's not a dependency tree generation tool.

I built this and many of the other libraries for https://github.com/mrjoelkemp/dependents without really knowing that Madge was tackling a subset of my needs. Ideally, I would have extracted the tree-generation stuff from Madge, but I took a bottom-up approach of building core libraries used for other parts of Dependents that were also leveraged in dependency-tree.

**Comment by marthinus-engelbrecht** [comment]
Cool. Makes sense to me. I like bottom up. I was looking at `madge`, and I was like "ok this is pretty cool, but I don't really need all the visualisation stuff". It would be really cool to see node-dependency-tree be used by `madge`.

**Comment by marthinus-engelbrecht** [comment]
We have a slight problem. The System.js config file isn't json, and you actually have to call `System.config()` inside it to set it up. So to get hold of the config object inside filing-cabinet it would have to know about SystemJS, at least if we want it to be passed in as a command line argument. I created an issue with SystemJS, systemjs/systemjs#1140, let's see what they say.

**Comment by mrjoelkemp** [comment]
Thanks for looking into it. Check out
https://www.npmjs.com/package/requirejs-config-file for ideas on a
scrappier way of parsing the config without systemjs. The linked module is
for requirejs, but the technique is applicable.

**Comment by marthinus-engelbrecht** [comment]
Ok, closed the system js issue. The [system-builder](https://github.com/systemjs/builder) gives us all that we need. I've forked [filling-cabinet](https://github.com/marthinus-engelbrecht/node-filing-cabinet), will be adding some code soon.

**Comment by mrjoelkemp** [comment]
Sounds awesome! Thanks for sticking with this!

**Comment by mrjoelkemp** [comment]
@marthinus-engelbrecht Hey! Any progress on the SystemJS front? I just landed webpack support in node-dependency-tree and was thinking about tackling SystemJS. Any help is appreciated.

**Comment by marthinus-engelbrecht** [comment]
@mrjoelkemp Yes there has been. Sorry, I've been a bit swamped with work. You can take a look at it [here](https://github.com/marthinus-engelbrecht/systemjs-absolute-path-resolver). Will see if I can get some work done this weekend. I played around a bit as well with generating [json-graph](https://github.com/jsongraph/json-graph-specification) and then transpiling it to a dot format and creating a graph with [graphviz](http://www.graphviz.org/)

**Comment by mrjoelkemp** [comment]
@marthinus-engelbrecht Awesome! It looks really good. I'd definitely use it within filing-cabinet (once https://github.com/marthinus-engelbrecht/systemjs-absolute-path-resolver/issues/1 has been addressed). Thanks for the update!
