### ISSUE TITLE
webpack module resolution fails silently

### ISSUE THREAD

**Issue by pcardune** [dependents/node-dependency-tree#53]
I've been generating a lot of dependency graphs which upon closer inspection are missing some very important modules! After sleuthing through this library and the libraries that it uses, I discovered that the missing modules could not be resolved! This was kind of painful because the failures are silenced and there doesn't appear to be an option to make them not silent. I ended up using `DEBUG=cabinet` to get the stack traces, but that was a pretty hidden feature.

Either module resolution errors should not be silent (unless some explicit quiet flag is passed in) or there should be a big warning that your dependency graph might be incomplete of modules fail to resolve.

What do you think?

**Comment by mrjoelkemp** [comment]
Thanks for filing the issue and looking through the code. 

Would supplying an array to the [`nonExistent` option](https://github.com/dependents/node-dependency-tree/#usage) suffice for surfacing any modules that could not be resolved?

On one hand, I'd like for bugs in module resolution to fail fast. On the other hand, I'd like the tool to still be usable even when it has resolution bugs. I've opted for making the tool work well for the known use cases on known codebases; however, it's always the case where other codebases will find weaknesses in the lib. I'm open to discussing some sort of `failFast` (name up for debate) flag that allows resolution errors to throw an exception. Putting in an opt-in `quiet` flag would be a breaking change that I'd like to avoid if we can.

I'm open to a PR that adds notes to the readme that you think would make it clearer to the user how  resolution errors affect the resulting tree. I agree that the pitfalls aren't explicit.

**Comment by pcardune** [comment]
The `nonExistent` option would probably work. Perhaps [madge](https://github.com/pahen/madge) should be using this. I will submit some pull requests.

**Comment by mrjoelkemp** [comment]
Glad to hear that `nonExistent` solves your problem (cc @j-lee)! 

Thanks so much for advocating for more visibility into what the tool is doing. You're saving other users the headache.
