### ISSUE TITLE
Windows bug

### ISSUE THREAD

**Issue by ghost** [dependents/node-dependency-tree#71]
import 'assets/styles/default.scss'; working in macOS, but not working in Windows. Path doesn't resolve and dependencies not found.

**Comment by TimvdEijnden** [comment]
Might be fixed by https://github.com/dependents/node-dependency-tree/pull/107

**Comment by XhmikosR** [comment]
We now have Windows CI and tests pass. Feel free to make a new issue if the issue persists or even better provide a PR.
