### ISSUE TITLE
How about support ES6 tree shaking

### ISSUE THREAD

**Issue by lichenhao** [dependents/node-dependency-tree#74]
For example:

```javascript
// mod-a.js
export const a = (x) => x + 1
export const b = (x) => x - 1
export const c = (x) => x * 1
```

```javascript
// mod-b.js
import {a, b} from "mod-a"
export const n = (x) => a(b(x))
```

```javascript
// output
{
  file: 'mod-b.js',
  exports: ['n'],
  depends: [{
    file: 'mod-a.js',
    exports: ['a', 'b', 'c'],
    used: ['a', 'b']
  }]
}
```

**Comment by mrjoelkemp** [comment]
Thanks for contributing! I think that level of granularity is useful, but doesn't fit well within this particular module. Dependency tree yields the tree as it pertains to the filesystem, whereas your proposal is more for import/export descriptions within a dependency tree hierarchy.

You could likely build a module that uses this one to do a second pass over the files to extract your desired output. If you need better perf, then doing your file analysis plus tree generation in a single pass is the path forward.

I also think this module carries around the baggage of amd and commonjs, which could be streamlined and simplified. 

I'll close this as a wontfix, but hopefully the above details are helpful.
