### ISSUE TITLE
Support tsconfig (for typescript path aliases configuration)

### ISSUE THREAD

**Issue by bloadvenro** [dependents/node-dependency-tree#83]
Hello! I came from madge library source code attempting to find the answer "How to resolve typescript import path aliases" :)

Standard import produces correct graph, but imports like `import { Omit } from '~/types/Omit';` are't tracked.

Thank you

**Comment by mrjoelkemp** [comment]
Hey @bloadvenro. I added `tsConfig` support in #93. Feel free to give it a spin and let me know if that resolves your tilde import.

**Comment by tatthien** [comment]
I've countered the same problem too. `@/` alias cannot be resolved.

**Comment by scott1028** [comment]
same problem encounter
