### ISSUE TITLE
Bumping filing-cabinet version to 2.0.1

### ISSUE THREAD

**Issue by antochiw** [dependents/node-dependency-tree#89]
`Filing-cabinet` dependency had a TS error when trying to reassign a `const` variable introduced on v1.14.4. This issue was fixed on `filing-cabinet` v2.0.1 but as the minimum required version on `dependency-tree` is v1.14.3, if you happened to download any version between v1.14.4 and 2.0.0 you would get an error.

Bumping `filing-cabinet` minimum version to `2.0.1` on the next `dependency-tree` upgrade would eliminate this issue.

**Comment by mrjoelkemp** [comment]
Resolved in #91. Thanks for filing!
